### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Gogenator** [Whales/edigotia#3]
After download and successfully "make" i have sigmentation fault after start.

**Comment by Whales** [comment]
Can you please provide a backtrace?

You can get one by running the program inside gdb (<code>gdb edigotia</code>; at the (gdb) prompt enter "r"; after the segfault enter "bt").

**Comment by Whales** [comment]
Oh, if this is not the first time you built the game, you may need to run "make clean" to refresh data.  Please try that if it applies!

**Comment by 8bitKittyKat** [comment]
I ran into the same issue myself, on my first and subsequent builds.  All builds (after running `make clean`, of course) yielded the same results.

```
Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106 ../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff7745ee5 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000004b62cc in Race_datum::add_city_names (this=0x7a66f0, pos=...) at race.cpp:91
#3  0x00000000004b9c7b in init_races () at race_data.cpp:157
#4  0x000000000046089d in init_all_data () at init.cpp:19
#5  0x0000000000495665 in main () at main.cpp:23
(gdb)
```

**Comment by Adapts** [comment]
glad to say that b7d160a1builds, starts, creates world, city, routes, saves and reloads for me. didn't get to look closer yet. awed as usual though :+1: 

$ uname -a
Linux adapts 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux

**Comment by Whales** [comment]
KittyTristy, what is your platform?  It looks like this could be a problem with a missing library on your system - I've seen similar with MinGW in the past.

**Comment by 8bitKittyKat** [comment]
@Whales 
`Linux tristy-xubuntu 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Adapts** [comment]
googling "ubuntu package sysdeps x86_64" it seem like you might need to install glib-c (and maybe a few more things) until your system has all the bits.  post a list!
